version: '3.8'

services:
  simple-one-api:
    image: fighter2011/simple-one-api:latest
    container_name: simple-one-api
    ports:
      - "9090:9090"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
#    restart: unless-stopped